### ISSUE TITLE
Crashes when using the Undo tool

### ISSUE THREAD

**Issue by JDRLGaming** [HielkeMinecraft/OpenNoteBlockStudio#116] opened 2020-01-18 16:23 UTC
At random points during the production of a note block song, Open Note Block Studio will occasionally crash when trying to undo a part of a song. sometimes this happens after only using the tool once and sometimes it happens when using the tool more than once.

**Comment by Bentroen** [comment] 2020-01-18 17:35
Duplicate of #115

**Closed by Bentroen** 2020-01-18 17:35 UTC
Labels: bug
