### ISSUE TITLE
MP3 export quality

### ISSUE THREAD

**Issue by ProjectSketchOfficial** [HielkeMinecraft/OpenNoteBlockStudio#98] opened 2019-12-20 23:44 UTC
**Describe the bug**
When I export a song as an MP3, the quality is terrible. There is way too much distortion and turning down the volume of each layer a lot doesn't get rid of it.

**To Reproduce**
1. Export your song as an MP3
2. Select "yes" when it asks you to open it. Listen to the song and you can hear distortion especially in the "snare drum" (sand/gravel)

**Expected behavior**
The song should play the same way as an MP3 as it plays in Note Block Studio.

**Comment by Bentroen** [comment] 2019-12-30 20:36
Duplicate of #77. The MP3 export should see some improvements soon. :)

**Closed by Bentroen** 2019-12-30 20:36 UTC
Labels: bug
