### ISSUE TITLE
repeater delay not set up properly

### ISSUE THREAD

**Issue by junyong0716** [HielkeMinecraft/OpenNoteBlockStudio#249] opened 2021-05-25 03:45 UTC
**Describe the bug**
If i create a song which required 3 or more layers when exported as a schemetic file, the repeater located at the front doesnt set up properly and makes the song terrible.

**To Reproduce**
1. create a song which requires 3+ layers on nbs
2. export as schemetic
3. use mcedit/worldedit to load it into the world
4. listen to song

**Expected behavior**
the repeater should turn on all at once.

**Screenshots**
https://youtu.be/v_dEkjQOMB8
this is a video explaining it

**Additional context**
plz fix this i dont want to manually change all the repeaters

**Comment by Bentroen** [comment] 2021-07-30 00:49
Duplicate of #105

**Closed by Bentroen** 2021-07-30 00:49 UTC
Labels: Type: Bug
