### ISSUE TITLE
Exporting to mp3 does not keep panning

### ISSUE THREAD

**Issue by Disturbedmosquito** [HielkeMinecraft/OpenNoteBlockStudio#230] opened 2021-01-25 15:04 UTC
**Describe the bug**
When exporting a note block song to mp3, the panning of the notes is not conserved and everything is in stereo.

**To Reproduce**
1. Just export a song and listen

**Expected behavior**
I was expecting the mp3 file to sound exactly like the note block song in note block studio, and i thing it should be doing that.

**Additional context**
Maybe this is not a bug with note block studio and something weird that happens with exporting, I have no idea. If someone knows how to export and conserve the panning please tell me.

**Comment by CubixL** [comment] 2021-01-25 15:06
Yeah, this issue has been reported quite a lot.
For now, try using an external program for MP3 exports (I use Audacity), because the built-in function is really weird. In addition to panning, it also weirdly pitches certain instruments for no reason, and makes the whole thing sound off.

**Comment by Bentroen** [comment] 2021-01-31 20:57
Thanks for reporting! The MP3 export function dates back from before panning existed in NBS, so it doesn't take it into account. That function is currently undergoing a rewrite to not only support panning, but also fix clipping and distortions in pitch (see #77 and #212).

I'll close this as a duplicate of #87, since it's the same request. You can track the progress on this feature there :)

**Closed by Bentroen** 2021-01-31 20:57 UTC

**Comment by Disturbedmosquito** [comment] 2021-02-07 14:06
Didn’t check in a while, but ok thanks!
