### ISSUE TITLE
The window when i open it is very, very small, and it is hard to see anything.

### ISSUE THREAD

**Issue by Gold-Gaming** [HielkeMinecraft/OpenNoteBlockStudio#148] opened 2020-04-21 19:29 UTC
**Describe the bug**
Everything is extremely small and hard to use.

**To Reproduce**
Just opening the software. I am using a Surface Pro 4, but I don't think that should be an issue.

**Screenshots**
![Screenshot (9)](https://user-images.githubusercontent.com/64101202/79905655-6b4c8c80-83cb-11ea-8a71-1d0486e22cdc.png)
![Screenshot (10)](https://user-images.githubusercontent.com/64101202/79905657-6d165000-83cb-11ea-8e69-7183d896eb06.png)
![Screenshot (11)](https://user-images.githubusercontent.com/64101202/79905659-6daee680-83cb-11ea-9cda-acd258c6dcbd.png)

**Comment by Bentroen** [comment] 2020-04-21 21:01
Duplicate of #31.
The program currently has no proper support for high DPI displays. As a workaround, you can set a custom display scale in the Windows settings to make the window appear larger, though it should be a bit blurry.

**Closed by Bentroen** 2020-04-21 21:01 UTC
Labels: bug
