### ISSUE TITLE
No high-res monitor support

### ISSUE THREAD

**Issue by EnderIzzy124** [HielkeMinecraft/OpenNoteBlockStudio#252] opened 2021-06-27 07:52 UTC
I've got a very, very large monitor that I got as a christmas gift. As a result, the gui is extremely small, and I can't seem to find a way to scale it up. It should probably go in appearance.

![image](https://user-images.githubusercontent.com/39423124/123536926-07be9d00-d6fb-11eb-908e-469b67cfe15e.png)

**Comment by MericGit** [comment] 2021-06-27 07:56
Duplicate of #31
The update is coming. Progress is a bit stalled as the rewrite occurs, but it'll be out at some point.

**Closed** 2021-07-23 10:16 UTC
Labels: Status: Duplicate
