### ISSUE TITLE
Issue with exporting datapacks

### ISSUE THREAD

**Issue by Geek202** [HielkeMinecraft/OpenNoteBlockStudio#43] opened 2019-06-11 15:37 UTC
When attempting to export a datapack of a noteblock song the program crashes with this error:
![image](https://user-images.githubusercontent.com/23531706/59285844-8f492880-8c66-11e9-9576-4c26360dda29.png)

Program version: 3.4.0

**Comment by ShinkoNet** [comment] 2019-06-25 14:16
Can you attack the .nbs file? Let me take a look

Try scrolling to the end of the song, and add a random note at the bottom layer (scroll down). Save, delete the note, save again, then retry.

**Comment by Geek202** [comment] 2019-06-27 14:58
Tried adding another note, still crashes and its imported from a MIDI file.
Sorry, GitHub won't let me attach .nbs files though.

**Comment by HielkeMinecraft** [comment] 2019-07-28 16:37
Can't reproduce this. We need your .nbs file in order to fix this. If you can't upload it, upload it to google Drive or something and post the link here. 

Otherwise this issue will be closed.

**Comment by Geek202** [comment] 2019-07-29 09:32
Its a MIDI imported version of Bohemian Rhapsody and I was just testing out NBS.

NBS file: https://www.dropbox.com/s/alk1ho4q4t4265u/test.nbs?dl=0

**Comment by ShinkoNet** [comment] 2019-07-29 11:58
Seems it could be an issue with MIDI importing. Mind if you send the MIDI too?

**Comment by Geek202** [comment] 2019-07-30 08:48
Crashed first time trying to export datapack but after relaunching and trying again, the datapack was exported.
MIDI file: https://www.dropbox.com/s/7pcopbt7netvc24/Queen_-_Bohemian_Rhapsody.mid?dl=0

**Comment by HielkeMinecraft** [comment] 2019-08-07 22:28
That's even weirder. Why would it work one time, and not the other? It keeps crashing on me. Looks like there is something going wrong when generating the nbs file. (MIDI import). Can't figure out what though...

**Comment by ShinkoNet** [comment] 2019-10-07 21:30
Should be fixed in the next upcoming update. Feel free to reopen if it still crashes.

**Closed by ShinkoNet** 2019-10-07 21:30 UTC
Labels: bug
