### ISSUE TITLE
Minecraft ONBS Translate issue

### ISSUE THREAD

**Issue by MyatkinCat** [HielkeMinecraft/OpenNoteBlockStudio#185] opened 2020-08-26 07:53 UTC
Hello! I am a representative of the Russian audience of ONBS.

It was more convenient for me to use the Russian version of ONBS, and I wanted to translate it.
Since the program does not support multilanguage, I had to dig into data.win, but it was not successful.
I would like the program to support multilanguage and for all files with translations to be in a separate folder.

Kind regards,
Myatkin Cat

**Comment by Bentroen** [comment] 2020-08-26 09:36
Hello! Thanks for reaching out. It makes me happy to know ONBS has a user base all the way there in Russia :)

We've been wanting to make the program translatable for a while, and you're not the first one to request this. However, due to the 9-year old codebase and many limitations of the engine we're using, it's pretty much impossible to implement translations in the current version.

That being said, we're currently in the process of rewriting the program from scratch in another engine (translations being one of many, many reasons). This new version will not only be fully translatable, but the strings will be uploaded to a translation platform so everyone can contribute. We aim to release this version in a few months if everything goes well (you can follow #4 for updates on this).

Thanks for your interest in helping the project! Stay tuned, it will be possible in the near future. :)

**Comment by MyatkinCat** [comment] 2020-08-30 11:12
I am pleased to hear this from one of the developers (probably).
Thanks for such a useful program!
I hope the new multilingual version of the program will not keep itself waiting long :)

Kind regards,
Мяткин Кот (Myatkin Cat on Russian)

**Comment by MyatkinCat** [comment] 2020-09-01 13:05
I understood the circumstances of the situation with the program, I will wait for updates

**Comment by MyatkinCat** [comment] 2020-09-01 13:19
And one more question: Can I get access to beta versions of the program?

**Comment by Bentroen** [comment] 2020-09-04 11:58
At this moment the program is in a closed development stage, until we have something that minimally works. Once we get to that point, the code will be released here on GitHub (just like the current version), and you'll be able to clone the project and run it directly from the source. We currently have no plans to release beta versions, although we might consider that possibility prior to the official release. :)

**Comment by Bentroen** [comment] 2020-09-11 09:21
Closing as a duplicate of #112.

**Closed by Bentroen** 2020-09-11 09:21 UTC
