### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tristan2998** [HielkeMinecraft/OpenNoteBlockStudio#32] opened 2019-05-29 11:22 UTC
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object obj_controller:

Attempting to read from outside the buffer, returning 0
at gml_Script_buffer_read_byte
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_buffer_read_byte (line -1)
gml_Script_buffer_read_string_int
gml_Script_load_settings
gml_Script_control_create
gml_Object_obj_controller_Create_0

Similar to other cases, but a little different, like #8

**Comment by ShinkoNet** [comment] 2019-06-01 07:43
Have you tried deleting your settings.file in /data?

**Comment by tristan2998** [comment] 2019-06-01 07:54
Will give it a go. Also I didn't realise the fan port was made by
shinkonet. I love your midis!

**Comment by DarkBrave** [comment] 2019-06-04 11:52
this helped me! Thanks!

**Comment by XGMCLOLCrazE** [comment] 2019-06-05 17:08
I was having this same issue, but I can't find settings.file nor /data.

Where is it located?

**Comment by koca2000** [comment] 2019-06-21 21:49
Duplicate of #6

**Closed** 2019-06-25 12:29 UTC

**Comment by tristan2998** [comment] 2019-06-25 17:31
Thanks again for the help!
