### ISSUE TITLE
Typing in Any Text Field quickly doesn't work well

### ISSUE THREAD

**Issue by CreeperPookie** [HielkeMinecraft/OpenNoteBlockStudio#266] opened 2021-09-25 23:19 UTC
**Describe the bug**
Hello! Something I noticed while making a song is that if you type into a text field fast, a lot of letters aren't registered at all. 

**To Reproduce**
1. Click in any text field
2. Try to type quickly
3. Examine the text that was put in the field

**Expected behavior**
Although I know that some people may type faster than others, I would expect it to register all or most of the letters I type, especially when making layer descriptions.

**Comment by Encode42** [comment] 2021-09-26 02:41
Duplicate of #123

**Closed** 2021-09-26 04:10 UTC
Labels: Type: Bug, Status: Duplicate
