### ISSUE TITLE
Variable Index [34] out of range [34]

### ISSUE THREAD

**Issue by kebufu** [HielkeMinecraft/OpenNoteBlockStudio#246] opened 2021-05-16 05:08 UTC
**Describe the bug**
```
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_menu:

Variable Index [34] out of range [34]
at gml_Script_selection_code_update
############################################################################################
gml_Script_selection_code_update (line -1)
gml_Script_selection_compress
gml_Script_menu_click
gml_Script_menu_draw
gml_Object_obj_menu_Draw_0

```

**To Reproduce**
1. Select all notes.
2. Click on 'compress selection'
3. Click again.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31839741/118386074-3ef35600-b647-11eb-9332-c5451fe213a7.png)

**Additional context**
[冒険でしょでしょ？(1).zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/6488728/1.zip)

**Comment by Bentroen** [comment] 2021-05-19 07:41
Thank you for your report! This issue is a duplicate of #44, so I'm going to close this one so we can keep track of it there.

**Closed by Bentroen** 2021-05-19 07:41 UTC
