### ISSUE TITLE
Can you release a linux version if it is possible?

### ISSUE THREAD

**Issue by freeze-dolphin** [HielkeMinecraft/OpenNoteBlockStudio#132] opened 2020-03-18 08:42 UTC
**Is your feature request related to a problem? Please describe.**
Linux users cannot use NoteBlockStudio at allll!
Even run it by using the wine!

**Describe the enhancement you'd like**
Can you release a linux version if it is possible?
I have seen that **GameMaker Studio 2 has supported ubuntu exporting**

**Additional context**
No.

**Comment by treier57lol** [comment] 2020-03-18 19:30
Duplicate of #4, and it seems that a Linux port is maybe possible? Also yes, running it on Wine doesn't work and the main contributors know this (#93). I'm not getting any sound output on Manjaro, but that's probably to be expected.

ONBS is dependant on a lot of Windows only libraries, so a straight port is pretty hard to get working properly. The absolute best solution would probably be to just rewrite the entire program in a cross-platform friendly language, but then a lot of the code would be unsalvageable and rewriting a program from scratch isn't a one day task either, but it could be done.

The source code for the libraries exist and could be ported over, and it seems someone got it working, but they can't legally share it. https://github.com/HielkeMinecraft/OpenNoteBlockStudio/issues/4#issuecomment-508302527

And yes, GMS2 should have the support for building for Linux, but the libraries seem to be the main roadblock.

Anyway, you should go over to #4 and ask there for any updates on Linux support, but the story is probably going to be the same as I just wrote out. But who knows, maybe an official port could be possible?

**Comment by Bentroen** [comment] 2020-04-03 06:41
As pointed out by @treier57lol, while Game Maker: Studio does offer support to Ubuntu, the program relies on Windows-only libraries that provide most of the core functionality. While it _is_ possible to replace these libraries with cross-platform alternatives, it would take a lot of time to get it to minimally work, and the program would still be missing a lot of side features. I'd rather spend this time in rewriting the program from scratch in a cross-platform framework, which is something it is needing anyway.
I'm closing this is as a duplicate. Any further news on a future Linux port will be handled in #4.

**Closed by Bentroen** 2020-04-03 06:41 UTC
Labels: enhancement
