### ISSUE TITLE
Autosaving overwrites/erases your files when you have multiple instances of ONBS open

### ISSUE THREAD

**Issue by CubixL** [HielkeMinecraft/OpenNoteBlockStudio#190] opened 2020-09-04 19:50 UTC
**Describe the bug**
Opening a .nbs file externally while still having ONBS open somewhere else overwrites your file, when selecting certain options on the autosaving menu that pops up.

**To Reproduce**
1. Open file 1 using either ONBS's menu or file explorer.
2. Using file explorer, open file 2. This opens up a second window for ONBS
3. File 2 opens up an auto-recovery menu. From there you can choose multiple options.
4. You click on "Yes" in the auto-recovery menu.
This opens up another menu, labeled "Confirm", which asks you if you want to save File 2's changes. You click on "Yes" again.
This overwrites File 2's data with File 1's.

I fiddled around with the other options (such as clicking "No" on the auto-recovery menu or the confirm menu), but they didn't seem to harm my files.

Unintentionally, sometimes I open up my computer and find out that one of my projects has been erased (this happened three times now?) I'm not sure if this is related with the issue, and I don't know how it happens (and now I have a good reason to keep backups), but it's definitely something that needs to be fixed in future updates, because this is really annoying.

**Comment by CubixL** [comment] 2020-09-07 21:52
Okay, my file got erased again, but this time I have the details. Upon opening a new song from ONBS, I am greeted with the screenshot below.
![ONBSerror](https://user-images.githubusercontent.com/61438430/92417808-28007980-f132-11ea-8179-22cf4c90603f.PNG)
Pressing OK closes the program. You can still open the file using any means, but they all tell me that the file cannot be found and that I must try again. Only then will the file truly be erased and never to be seen again. It's not even in the Recycle Bin.

I am SO happy I keep backups. # of total files erased: 4

**Comment by Bentroen** [comment] 2020-09-26 20:31
Although it was reported before, I'll mark this as a duplicate of #196 since I'm tracking the progress there. Really sorry for any work loss that this issue may have caused.

Also, did you find the Runtime Error screen to be related to this in any way? I absolutely can't figure out why it happens or what's causing it, so it's intriguing to see a screenhot of it in that context.

**Comment by CubixL** [comment] 2020-09-27 01:59
I have no clue what's causing it. Here's a detailed version of everything I click.
1. I open the file menu
2. I click on "Open song"
3. I double click a song
4. "Load song" tab closes
5. Runtime Error appears
6. I press OK
7. ONBS closes
8. My file is mysteriously missing

Maybe it's related to the fact that I keep it open for long periods of time, but really I have no idea why this happens.

**Closed** 2020-10-22 05:03 UTC
Labels: Status: Duplicate, Type: Bug
