### ISSUE TITLE
Datapack Export Crash

### ISSUE THREAD

**Issue by Trevorsleeping** [HielkeMinecraft/OpenNoteBlockStudio#81] opened 2019-08-25 01:46 UTC
![image](https://user-images.githubusercontent.com/54488659/63644489-129be700-c6b8-11e9-9afe-4add3a9503c7.png)
Hello. I'm having trouble exporting a datapack without Noteblock Studio crashing. Using version 3.6.0.
.nbs file:
https://www.dropbox.com/s/kz132kki821h5c9/UniversalCollapse.nbs?dl=0

**Comment by ShinkoNet** [comment] 2019-08-25 03:15
Replicated by using "UniversalCollapse" as the datapack's name. When exporting with the words "test" or some other simple name, it works fine.

**Comment by ShinkoNet** [comment] 2019-08-25 03:22
Dupe of #43

**Closed by ShinkoNet** 2019-08-25 03:22 UTC
Labels: duplicate
