### ISSUE TITLE
Please make it so you can change the size of the work space

### ISSUE THREAD

**Issue by Github1BenClark1** [HielkeMinecraft/OpenNoteBlockStudio#133] opened 2020-03-18 09:38 UTC
I would like it if you could maybe make it so you can change the size of the work space because mine looks tiny (my screen resolution is 3000x2000) and I can't physically use it.

**Comment by Bentroen** [comment] 2020-04-03 06:30
Duplicate of #31.

**Closed by Bentroen** 2020-04-03 06:30 UTC
Labels: enhancement
