### ISSUE TITLE
MP3 exports sound bad when large amounts of notes are playing

### ISSUE THREAD

**Issue by CubixL** [HielkeMinecraft/OpenNoteBlockStudio#199] opened 2020-09-16 00:19 UTC
When I mean "large amounts" I mean when the active sound counter (disabled by default) goes over somewhere around 50. Once it reaches this point, it's very close to sounding like earrape. I'm not sure how you could improve this though, it sounds like it can't handle that much noise at the same time. Overall, recording your computer sounds way better.

Side note: The mp3 also does not play stereo effects.

**Comment by Bentroen** [comment] 2020-09-16 01:05
Thanks for recording! Oops, reporting.

Both the bad export quality and the lack of stereo support are known issues; the reason we haven't fixed them before is that it requires changing the MP3 export DLL which is not exactly an easy task. However, we'll remove that dependency on version 4 and it should be much easier to fix those issues. :)

I'm closing as a duplicate of #77.

**Closed by Bentroen** 2020-09-16 01:05 UTC
