### ISSUE TITLE
Fatal Error...

### ISSUE THREAD

**Issue by PankakeFrier** [HielkeMinecraft/OpenNoteBlockStudio#45] opened 2019-06-16 13:05 UTC
![Minecraft_Note_Block_Studio_S7xI5ObB1D](https://user-images.githubusercontent.com/51881033/59564518-c2f9c900-903f-11e9-84b9-163163218ba5.png)
Not sure what else to say... I just installed it and opened it up

**Comment by rex9135** [comment] 2019-06-18 20:41
I also have this issue, have you found a solution yet?

**Comment by manakusiar** [comment] 2019-06-19 19:19
is there any way to macke it work?

**Comment by HolyUngoy** [comment] 2019-06-19 23:33
I have this issue to.  Solution?

**Comment by koca2000** [comment] 2019-06-21 21:49
Duplicate of #6

**Comment by PankakeFrier** [comment] 2019-06-22 11:18
> Duplicate of #6
Unfortunately, I have reinstalled the program but it has not resolved anything

**Comment by ShinkoNet** [comment] 2019-06-25 12:25
Try to find wherever a "settings.file" file is, and delete it. That's the only way to fix this issue. If you uninstalled it, that file might have been left over, so make sure to search your computer for the file.

**Comment by HielkeMinecraft** [comment] 2019-06-27 12:42
Are you guys updating from before 3.3.6? I don't understand how there are still so many people with this issue...

**Closed** 2019-07-28 13:34 UTC
Labels: duplicate
