### ISSUE TITLE
Better Layer Volume Controls

### ISSUE THREAD

**Issue by jhaberland** [HielkeMinecraft/OpenNoteBlockStudio#114] opened 2020-01-14 23:15 UTC
**Is your feature request related to a problem? Please describe.**
Whenever I try to change the volume on any layer, I have no control. It either jumps to 0% or 100%.

**Describe the enhancement you'd like**
You should be able to either enter a number for the volume, or when you click on the volume it brings up a slider bar.

**Comment by Bentroen** [comment] 2020-01-15 06:55
Thanks for your report! This issue is a duplicate of #104, which is already fixed for the next update.

Typing values may be possible in the future, but it's not planned at the moment – with that issue fixed, you should be able to set layer volumes more accurately.

**Closed by Bentroen** 2020-01-15 06:55 UTC
Labels: enhancement
