### ISSUE TITLE
Time goes slower in new version

### ISSUE THREAD

**Issue by T0biasCZe** [HielkeMinecraft/OpenNoteBlockStudio#166] opened 2020-06-13 14:24 UTC
The song in new 3.7.2 version is slower than in 3.6, and its because the time is slower compared to windows time or old version time. One second in the editor is like 2seconds in real
adding video where i started the song in 3.7.2 version, and after 5seconds I launcher the same song in 3.6, after a while its ahead of the new version which started sooner
https://youtu.be/E8lt5k6fh-c

**Comment by Bentroen** [comment] 2020-06-16 09:09
Duplicate of #101. Good news: it was just fixed! :D

**Closed by Bentroen** 2020-06-16 09:09 UTC
