### ISSUE TITLE
Double click at .nbs file to open in program

### ISSUE THREAD

**Issue by octahedron80** [HielkeMinecraft/OpenNoteBlockStudio#83] opened 2019-08-27 15:44 UTC
The issue exists since the old version: double clicking at a .nbs file but the song is not loaded. It does run the program but the song does not sit in place and I must browse for the .nbs file again. This should be solved by supporting .nbs file parameter in command line.

**Comment by HielkeMinecraft** [comment] 2019-08-27 18:04
Not a bug, this never worked in NBS. It would be a nice enhancement though :)

**Comment by KabanFriends** [comment] 2019-10-05 13:19
I want this feature too.
GMS1 and GMS2 have support for command line parameters, so it must be possible.
(Maybe related to https://docs.yoyogames.com/source/dadiospice/002_reference/miscellaneous/parameter_string.html this thing)

Some note about how Windows runs application when the app is assigned to a file
it runs a command like this when you double click on a file:
`application.exe "c:/nice/folder/file.nbs"`

**Comment by Bentroen** [comment] 2019-10-09 03:34
Thanks for your input @KabanFriends, I got it working perfectly! This should be in the next version.

**Closed by Bentroen** 2019-10-09 03:34 UTC
Labels: enhancement
