### ISSUE TITLE
Expand/collapse boxes in toolbar on small window

### ISSUE THREAD

**Issue by TheCraftedGamer** [HielkeMinecraft/OpenNoteBlockStudio#155] opened 2020-05-18 05:15 UTC
the problem with these tabs that I noticed is when making the window smaller, some of the tools at the top disappear. another problem is that there is no way of closing these tabs. for instance say I didn't want to see the tools "edit note key", "edit note velocity", "edit note panning", and "edit note pitch. there is no way to close it or make it smaller.

to begin, the tabs could have a scrolling feature. when you hover your mouse over them and scroll, it will move left or right. and to help those who don't want to see the tools, add an option to customize the toolbar or add a box that will close/open the tools.

![ffffff](https://user-images.githubusercontent.com/65487821/82176536-43e6c380-9894-11ea-891d-843c12929703.PNG)

**Comment by Bentroen** [comment] 2020-05-18 05:41
This problem is due to the fact that the toolbar was designed to hold only 5 instruments, not 16. The best way to fix this would be to move the instruments to a new row, or yet a completely different place in the window.

I'm not fond of collapsible boxes, or hiding parts of the interface, simply because customization adds complexity. We'd have to add more buttons to control the interface, leading to even more bloat. I prefer having all (or most) options available at a glance.

There are things we can do to remedy it in the current version, but ultimately, it can only be properly fixed in the planned rewrite.

**Comment by TheCraftedGamer** [comment] 2020-05-18 05:55
> This problem is due to the fact that the toolbar was designed to hold only 5 instruments, not 16. The best way to fix this would be to move the instruments to a new row, or yet a completely different place in the window.
> 
> I'm not fond of collapsible boxes, or hiding parts of the interface, simply because customization adds complexity. We'd have to add more buttons to control what's visible, leading to even more bloat. I prefer having all (or most) options available at a glance.
> 
> There are things we can do to remedy it in the current version, but ultimately, it can only be properly fixed in the planned rewrite.

ah that makes sense

**Comment by Bentroen** [comment] 2020-06-26 07:51
I ended up adding an expandable/collapsible instrument box when there are too many to fit on the screen. Does not look all that bad, and it removes a lot of the clutter from the 16+ instrument buttons!
[![Image](https://i.gyazo.com/b0c3a66c2fe7f06fb1e43250d01e510f.gif)](https://gyazo.com/b0c3a66c2fe7f06fb1e43250d01e510f)
(also, these icons are just temporary haha)

**Closed** 2020-07-02 11:24 UTC
Labels: Status: Resolved, Type: Enhancement
