### ISSUE TITLE
Add Export to MIDI Option

### ISSUE THREAD

**Issue by CreeperPookie** [HielkeMinecraft/OpenNoteBlockStudio#188] opened 2020-08-30 02:17 UTC
When trying to convert a .midi or .mid file into a Minecraft Note Block Song is a really nice feature, and (for small songs) is very useful. However, sometimes I would like to export **to** MIDI, instead of from. Typically online converters do a horrible job, and usually I'm not using any custom instruments, just the vanilla ones. For non-custom instruments, is there any way to add a "Export to MIDI" option?

**Comment by Bentroen** [comment] 2020-09-01 09:42
Duplicate of #13 
This used to be a feature long before ONBS, but it had to be removed on the migration from GameMaker 8 to GameMaker: Studio. We do plan to re-add it in the near future. For now, you can use the 'Save options' feature to save your song in the Classic version, then use a pre-ONBS version to export to MIDI. Just go [here](https://stuffbydavid.com/mcnbs) and click 'Download older version' at the bottom of the page. :)

**Closed** 2020-09-02 12:09 UTC
Labels: Status: Duplicate, Type: Enhancement

**Comment by T0biasCZe** [comment] 2024-01-11 19:10
for those finding this issue from google, since the official website doesnt have the old version download anymore, here is the link from web archive...
http://web.archive.org/web/20190521202300/https://www.stuffbydavid.com/dl/mcnbs-zip-321
